name: contrastner
channels:
  - nvidia
  - pytorch
  - plotly
  - conda-forge
  - defaults
dependencies:
  - python=3.11.5
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - wandb
  - pytorch
  - transformers
  - datasets
  - plotly=5.20.0
  # - pytorch-cuda=12.1
  - pip
  - pip:
    - flair
    - jupyter
    - -e .
